djtest/urls.py
from django.conf.urls.defaults import patterns, include, url


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'blog.views.main', name='home'),
    url(r"^(\d+)/$", "blog.views.post", name='viewpost'),
    url(r"^add_comment/(\d+)/$", "blog.views.add_comment"),
    url(r'^admin/', include(admin.site.urls)),
)

djtest/blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import signals


class Post(models.Model):
    title = models.CharField(max_length=60)
    short_body = models.TextField(max_length=255)
    body = models.TextField()
    comment_count = models.IntegerField(editable=False, default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    confirmed = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s: %s' % (self.post, self.author)


def countcommentonsave(sender, instance, created, **kwargs):
    post = instance.post
    post.comment_count = \
        Comment.objects.filter(post__id=post.id, confirmed=True).count()
    post.save()


def countcommentondelete(sender, instance, **kwargs):
    post = instance.post
    post.comment_count = \
        Comment.objects.filter(post__id=post.id, confirmed=True).count()
    post.save()


signals.post_save.connect(countcommentonsave, sender=Comment)
signals.post_delete.connect(countcommentondelete, sender=Comment)

djtest/blog/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ["post", "confirmed"]

djtest/blog/views.py
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.core.context_processors import csrf
from django.conf import settings

from .models import Post, Comment
from .forms import CommentForm


def post(request, pk):
    post = Post.objects.get(pk=pk)
    comments = Comment.objects.filter(post=post, confirmed=True)
    d = dict(
        post=post,
        comments=comments,
        form=CommentForm(),
        user=request.user
    )
    d.update(csrf(request))
    return render_to_response("blog/post.html", d)


def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        comment = CommentForm(request.POST)
        if comment.is_valid():
            newcomment = comment.save(commit=False)
            newcomment.post = post
            newcomment.save()
            return HttpResponseRedirect('/%s/' % pk)
    else:
        comment = CommentForm(request.POST, instance=comment)
    comments = Comment.objects.filter(post=post, confirmed=True)
    d = dict(post=post, comments=comments, form=comment)
    d.update(csrf(request))
    return render_to_response("blog/post.html", d)


def main(request):
    posts = Post.objects.all().order_by("-created")
    paginator = Paginator(posts, settings.POST_PER_PAGE)
    try:
        page = int(request.GET.get("page", '1'))
    except ValueError:
        page = 1

    try:
        posts = paginator.page(page)
    except (InvalidPage, EmptyPage):
        posts = paginator.page(paginator.num_pages)

    return render_to_response("blog/list.html",
        dict(
            posts=posts,
            post_list=posts.object_list
        )
    )

djtest/templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>

    <style type="text/css">
        * {
            color: #555;
            font-size: 0.95em;
        }

        #menu a {
            text-decoration: none;
            background: #eee;
            border-top: 1px solid #ccc;
            border-bottom: 1px solid #ccc;
            border-right: 2px solid #fff;
            padding-right: 3px;
            padding-left: 3px;
            color: #777;
            font-size: 0.9em;
        }

        a:hover {
            background: #eeebeb;
            border-top: 1px solid #aaa;
            border-bottom: 1px solid #aaa;
            color: #555;
        }

        #container { margin: auto; width: 800px; border: 0px solid; }
        p { font-size: 1.1em; }
        h3 { margin-right: 30px; display: inline; }
    </style>

</head>

<body>
    <div id="container">
        <div id="menu">
            {% block nav-global %}

                <!-- MENU -->
                <h3>Blog</h3>
                {% if user.is_staff %}
                <a href="{% url admin:index %}">Admin</a>
                     <a href="{% url admin:blog_post_add %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

djtest/templates/blog/list.html
{% extends "base.html" %}


{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .commentlink { text-align: right; }
        .step-links a { font-size: 0.89em; }
        .title {
            font-size: 1.4em; margin-top: 20px; border-bottom: 1px solid #ccc;
            padding-left: 4px; margin-left: 5px;
        }
        .pagination { margin-top: 20px; margin-left: -20px; }
    </style>
    <div class="main">

        <!-- Posts  -->
            {% for post in post_list %}
                <div class="title"><a href="{% url blog.views.post post.pk %}">{{ post.title }}</a></div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="body">{{ post.short_body|linebreaks }}</div>
                    <div class="commentlink">Comments ({{ post.comment_set.count }})</div>
                </ul>
            {% endfor %}

        <!-- Next/Prev page links  -->
        {% if not archive and posts.object_list and posts.paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href= "?page={{ posts.previous_page_number }}">prev &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ posts.number }} of {{ posts.paginator.num_pages }}
                </span>

                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}"> &gt;&gt; next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

    </div>

{% endblock %}

djtest/templates/blog/post.html
{% extends "base.html" %}

{% block content %}
    <style type="text/css">
        .main { margin-left: 25px; margin-top: 30px; }
        .time { font-size: 0.8em; margin-top: 2px; }
        .comment { border: 1px solid #eee; padding: 4px; margin-bottom: 12px; }
        .body { font-size: 1.1em; margin-top: 2px; }
        .messages { margin-left: 20px; }
        .title { font-size: 1.4em; margin-top: 20px; border-bottom: 1px solid #ccc; padding-left: 4px; }

        #addc { width: 508px; background: #f5f5f5; padding: 3px; padding-bottom: 8px;
            border-bottom: 1px dotted #aaa;
            }
        #cform { background: #f5f5f5; width: 506px; padding: 4px; padding-bottom: 0px; }
        #submit { text-align: right; margin-right: 50px; width: 500px; margin-top: -5px; }

        ul { margin-bottom: 30px; }
    </style>
    <div class="main">

        <!-- Post  -->
        <ul>
            <div class="title">{{ post.title }}</div>
            <ul>
                <div class="time">{{ post.created }}</div>
                <div class="body">{{ post.body }}</div>
            </ul>

            <!-- Comments  -->
            {% if comments %}
                <p>Comments:</p>
            {% endif %}

                {% for comment in comments %}
                <div class="comment">
                    <div class="time">{{ comment.created }} | {{ comment.author }}</div>
                    <div class="body">{{ comment.body|linebreaks }}</div>
                </div>
                {% endfor %}

            <div id="addc">Add a comment</div>
            <!-- Comment form  -->
            <form action="{% url blog.views.add_comment post.id %}" method="POST">{% csrf_token %}
                <div id="cform">
                    {% if form.errors %}
                    <p style="color: red;">Исправте следующие ошибки {{ form.errors }}</p>
                    {% endif %}
                    Author: {{ form.author }}{{ form.author.error }}
                    <p>{{ form.body|linebreaks }}{{ form.body.error }}</p>
                </div>
                <div id="submit"><input type="submit" value="Submit"></div>
            </form>
        </ul>

    </div>

{% endblock %}